server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/monitor
    username: monitor
    password: 123456
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  main:
    allow-circular-references: true
mybatis:
  mapper-locations: classpath:com/mapper/*.xml
  type-aliases-package: com.example.monitor.entity
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true