server:
  port: 443
  ssl:
    key-store: classpath:8175275_www.dpmonitor.top.pfx
    key-store-password: 0HP7A3ss
    key-store-type: PKCS12
    enabled: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.114.81.63:3306/monitor?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone =Asia/Shanghai
    username: monitor
    password: 123456
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  main:
    allow-circular-references: true
mybatis:
  mapper-locations: classpath:com/mapper/*.xml
  type-aliases-package: com.example.monitor.entity
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
jwt:
  header: "Authorization"
  tokenPrefix: ""
  secret: "qwertyuiop7418520"
  expireTime: 10080

